[project]
name = "scrap"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Tony123-tech", email = "tony1225leung@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "keyboard>=0.13.5",
    "playwright>=1.63.0",
    "pyautogui>=0.9.54",
    "pytest>=9.1.1",
]
